### ISSUE TITLE
Error CrudMatser

### ISSUE THREAD

**Issue by rafaelg21** [Gonzalo2310/CrudVue#2]
Buenas tardes saludos cordiales, 

Me descargue este proyecto para correlo en mi pc y hay un error al ejecutar el php artisan serve.

`$ php artisan serve
PHP Warning:  require(C:\xampp\htdocs\CrudVue-master\bootstrap/../vendor/autoload.php): failed to open stream: No suc
h file or directory in C:\xampp\htdocs\CrudVue-master\bootstrap\autoload.php on line 17

Warning: require(C:\xampp\htdocs\CrudVue-master\bootstrap/../vendor/autoload.php): failed to open stream: No such fil
e or directory in C:\xampp\htdocs\CrudVue-master\bootstrap\autoload.php on line 17
PHP Fatal error:  require(): Failed opening required 'C:\xampp\htdocs\CrudVue-master\bootstrap/../vendor/autoload.php
' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\CrudVue-master\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\CrudVue-master\bootstrap/../vendor/autoload.php' (in
clude_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\CrudVue-master\bootstrap\autoload.php on line 17
`
Y detecte que no esta la carpeta vendor de Laravel.

**Comment by Gonzalo2310** [comment]
Hola. Ningún proyecto de laravel incluirá la carpeta vendor principalmente porque seria el doble de tamaño y sobre todo porque eso debe instalarse en la maquina local. 

La solución es ir a la raíz del proyecto y escribir : **Composer install**
Luego tampoco olvides luego: **npm run dev**

Con esto el proyecto debería funcionar correctamente

Espero tu respuesta

**Comment by rafaelg21** [comment]
Muchisimas gracias amigo saludos, me copie una carpeta vendor de otro proyecto y no lo pude correr pero bueno, sin embargo estuve haciendo el tuto de tus post al cual quiero agradecerte por tan excelente tuto,pero me quede trabado ya que la actualizacion de la tabla cuando crero,elimino o edito no se hace entiempo real. sino que al mover cualquier link de la pagina o al abrir o cerra la modal es que veo el cambio de lo contrario no se visualiza el cambio en la tabla departamentos. 

Seguire haciendo el tutorial para ver si hay un error que me salte para departamentos o que se yo. 
pero alli me qude trabado. lo mas ilogico es que imprime en  console.log(answer.departures);    y alli si se ve el objeto nuevo cuando lo creo pero no se hace el cambio en la tabla. sino como le explique en la parte de arriba. 

Bueno se q es muy dificil q me pueda ayudar pero quizas le ha pasado y tenga la solución. de ante mano muchas gracias

**Comment by rafaelg21** [comment]
Listo amigo ya resolvi el problema de la recarga de la tabla departamentos, el problema es el siguiente no tenia declarado en el json el arreglo departures:[]

para que me funcionara realice este cambio que seguro me salte en algun lado del tutorial.

`
data: {
                menu: 0,
                modalGeneral: 0,
                titleModal: '',
                messageModal: '',
                modalDeparture: 0,
                titleDeparture: '',
                errorTitleDeparture: 0,
                departures:[]
            },
`

**Comment by Gonzalo2310** [comment]
Genial. Muchas gracias por tu interes.  Cerrare  el tema. Y de nuevo  gracias
